site_name: My Docs

site_url: https://Rishita95.github.io/rag-bootcamp

repo_url: https://github.com/Rishita95/rag-bootcamp
repo_name: Rishita95/rag-bootcamp

nav:
  - Home: index.md
  

theme:
  name: material
  features:
    - content.code.copy
  palette:  
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences